AWSTemplateFormatVersion: "2010-09-09"
Description: "This CloudFormation template creates resources required for 'talk-to-your-slide-deck' using Titan multimodal embeddings"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label: 
          default: Required Parameters
        Parameters:
          - OSCollectionName          
          - OSIndexName
    ParameterLabels:      
      OSCollectionName:
        default: OpenSearch vector index name
      OSIndexName:
        default: OpenSearch collection name

Parameters:
  OSCollectionName:
    Default: multimodaloscollection
    Type: String
    Description: Name of the Amazon OpenSearch Service Serverless (AOSS) collection
    MinLength: 1
    MaxLength: 63
    AllowedPattern: ^[a-z0-9](-*[a-z0-9])*
    ConstraintDescription: Must be lowercase or numbers with a length of 1-63 characters
  OSIndexName:
    Default: multimodalslidesindex
    Type: String
    Description: Name of the vector index in the Amazon OpenSearch Service Serverless (AOSS) collection

Resources:
  OSPolicy:
    Type: "AWS::IAM::RolePolicy"
    Properties:
      PolicyName: "ospolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "aoss:APIAccessAll"
              - "aoss:DashboardsAccessAll"
              - "aoss:BatchGetCollection"
            Resource: "*"
      RoleName: !Ref OSPipelineExecutionRole

  S3Policy:
    Type: "AWS::IAM::RolePolicy"
    DependsOn: SQSQueue
    Properties:
      PolicyName: "s3policy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Sid: "ReadFromS3"
          Effect: "Allow"
          Action: "s3:GetObject"
          Resource:
          - "arn:aws:s3:::sagemaker*"
        - Sid: "ReceiveAndDeleteSqsMessages"
          Effect: "Allow"
          Action:
          - "sqs:DeleteMessage"
          - "sqs:ReceiveMessage"
          - "sqs:ChangeMessageVisibility"
          Resource: !GetAtt SQSQueue.Arn
      RoleName: !Ref OSPipelineExecutionRole

  SecurityPolicy: 
    Type: "AWS::OpenSearchServerless::SecurityPolicy" 
    Properties: 
      Name: "encryptionpolicy"
      Type: "encryption" 
      Description: Encryption policy for OS collections 
      Policy: !Sub >-
                {"Rules":[{"ResourceType":"collection","Resource":["collection/${OSCollectionName}"]}],"AWSOwnedKey":true}

  NetworkPolicy: 
    Type: "AWS::OpenSearchServerless::SecurityPolicy" 
    Properties: 
      Name: "networkpolicy"
      Type: "network" 
      Description: Network policy for OS collections
<<<<<<< HEAD
      Policy: >-
                [{"Rules":[{"ResourceType":"collection","Resource":["collection/multimodaloscollection"]},{"ResourceType":"dashboard","Resource":["collection/multimodaloscollection"]}],"AllowFromPublic":true}]
=======
      Policy: !Sub >-
                [{"Rules":[{"ResourceType":"collection","Resource":["collection/${OSCollectionName}"]},
                {"ResourceType":"dashboard","Resource":["collection/${OSCollectionName}"]}],"AllowFromPublic":true}]
>>>>>>> d756ab2 (parameters)
  
  DataAccessAdminPolicy:
    Type: "AWS::OpenSearchServerless::AccessPolicy"
    Properties:
      Name: "dataaccessadminpolicy"
      Type: "data"
      Policy: !Sub >-
                [{"Description": "Data Admin access", "Rules": [{"ResourceType": "index", "Resource": ["index/*/*"], "Permission": ["aoss:*"]},
                {"ResourceType": "collection", "Resource": ["collection/${OSCollectionName}"], "Permission": ["aoss:*"]}],
                "Principal": ["arn:aws:iam::${AWS::AccountId}:role/Admin"]}]

  DataAccessPolicy:
    Type: "AWS::OpenSearchServerless::AccessPolicy"
    Properties:
      Name: "dataaccesspolicy"
      Type: "data"
      Policy: !Sub >-
          [{"Description": "Data access", "Rules": [{"ResourceType": "index", "Resource": ["index/*/*"], "Permission": ["aoss:*"]}],
          "Principal": ["${SMExecutionRole.Arn}", "${OSPipelineExecutionRole.Arn}"]}]

  SQSQueuePolicy: 
    Type: AWS::SQS::QueueInlinePolicy
    Properties: 
      Queue: !Ref SQSQueue
      PolicyDocument: 
        Statement: 
          Action: 
            - "SQS:SendMessage" 
            - "SQS:ReceiveMessage"
          Effect: "Allow"
          Resource: !Sub ${SQSQueue.Arn}
          Principal:  
            Service: "s3.amazonaws.com"
          Condition:
              StringEquals:
                aws:SourceAccount: !Sub ${AWS::AccountId}
              ArnLike:
                aws:SourceArn: !Sub "arn:aws:s3:*:*:sagemaker-${AWS::Region}-${AWS::AccountId}"

  SMExecutionRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      Policies:
        - PolicyName: AOSSAPIAccessAll
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - aoss:APIAccessAll
                Resource: !Sub "arn:aws:aoss:${AWS::Region}:${AWS::AccountId}:collection/*"
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "sagemaker.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonSageMakerFullAccess"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonS3FullAccess"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonOpenSearchServiceFullAccess"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonBedrockFullAccess"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AWSCloudFormationReadOnlyAccess"

  OSPipelineExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "osis-pipelines.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"

  SQSQueue: 
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: "InputfromS3"

  MultimodalNotebookInstance:
    Type: "AWS::SageMaker::NotebookInstance"
    Properties:
      InstanceType: "ml.t3.xlarge"
      VolumeSizeInGB: 200
      RoleArn: !GetAtt SMExecutionRole.Arn
      # DefaultCodeRepository: "https://github.com/aarora79/multimodal.git"

  MultimodalCollection:
    Type: "AWS::OpenSearchServerless::Collection"
    Properties:
      Name: !Ref OSCollectionName
      Type: "VECTORSEARCH"
      Description: "Embeddings collection"
    DependsOn: [SecurityPolicy, NetworkPolicy, DataAccessAdminPolicy, DataAccessPolicy]

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/vendedlogs/multimodalpipeline-${AWS::StackName}"

  MultimodalPipeline:
      Type: "AWS::OSIS::Pipeline"
      Properties:
        LogPublishingOptions:
          IsLoggingEnabled: true
          CloudWatchLogDestination:
            LogGroup: !Ref LogGroup
        MinUnits: 1
        MaxUnits: 2
        PipelineConfigurationBody: !Sub |
          version: "2"
          s3-pipeline:
            source:
              s3:
                notification_type: "sqs"
                codec:
                  json:
                sqs:
                  queue_url: ${SQSQueue}
                compression: "none"
                aws:
                  region: ${AWS::Region}
                  sts_role_arn: ${OSPipelineExecutionRole.Arn}
            processor:
            - date:
                destination: "@timestamp"
                from_time_received: true
            sink:
              - opensearch:
                  hosts: [${MultimodalCollection.CollectionEndpoint}]
                  index: ${OSIndexName}
                  aws:
                    serverless: true
                    serverless_options:
                      network_policy_name: ${NetworkPolicy}
                    sts_role_arn: ${OSPipelineExecutionRole.Arn}
                    region: ${AWS::Region}
        PipelineName: "multimodalpipeline"
Outputs:
  MultimodalNotebookInstanceId:
    Value: !Ref MultimodalNotebookInstance
  SQSQueueARN: 
    Description: "InputfromS3 SQS Queue ARN"
    Value: 
      !GetAtt SQSQueue.Arn
  SQSQueueURL: 
    Description: "InputfromS3 SQS Queue URL"
    Value: 
      !Ref SQSQueue
  MultimodalCollectionEndpoint:
    Value: 
      !GetAtt MultimodalCollection.CollectionEndpoint
  OpenSearchIndexName:
    Description: "OpenSearch Vector Index"
    Value: !Ref OSIndexName
